<?php

use Krystal\Form\Element;

?>

<form>
	<div class="well clearfix">
        <?php echo Element::hidden('advice[id]', $advice->getId()); ?>

		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('advice[title]', $advice->getTitle(), array('class' => 'form-control', 'placeholder' => $this->translate('Advice title'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>

		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Content'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::textarea('advice[content]', $advice->getContent()); ?>
			</div>
		</div>

		<div class="form-group clearfix">
			<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::checkbox('advice[published]', $advice->getPublished(), array('class' => 'form-control')); ?>
			</div>
		</div>
	</div>
	
	<?php if ($advice->getId()): ?>
	
	<button data-button="save" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
	
	<?php else: ?>

	<button data-button="add" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
	
	<?php endif; ?>
	
	<button data-button="cancel" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
</form>
