<?php defined('KRYSTAL') or die; ?>
<?php

use Krystal\Form\Element;

?>

<form data-group="advice">
	<div class="well">
        <?php echo Element::hidden('advice[id]', $advice->getId()); ?>

		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('advice[title]', $advice->getTitle(), array('class' => 'form-control', 'placeholder' => $this->translate('Advice title'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>

		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Icon'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('advice[icon]', $advice->getIcon(), array('class' => 'form-control', 'placeholder' => $this->translate('Optional icon'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>

		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Content'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::textarea('advice[content]', $advice->getContent(), array('data-wysiwyg' => 'true')); ?>
			</div>
		</div>

		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
			<div class="col-lg-10">
                <?php echo Element::checkbox('advice[published]', $advice->getPublished(), array('class' => 'form-control')); ?>
			</div>
		</div>
	</div>
	
	<?php if ($advice->getId()): ?>
	
	<button data-button="save" data-url="<?php echo $this->url('Advice:Admin:Advice@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" data-back-url="<?php echo $this->url('Advice:Admin:Advice@addAction'); ?>" data-url="<?php echo $this->url('Advice:Admin:Advice@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
	
	<?php else: ?>

	<button data-button="add" data-back-url="<?php echo $this->url('Advice:Admin:Advice@editAction', null); ?>" data-url="<?php echo $this->url('Advice:Admin:Advice@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" data-url="<?php echo $this->url('Advice:Admin:Advice@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add & Create new'); ?></button>
	
	<?php endif; ?>
	
	<button data-button="cancel" data-url="<?php echo $this->url('Advice:Admin:Advice@gridAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
	
</form>
