<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <?php $this->loadPartial('menu', array(
        'items' => array(
            'Advice:Admin:Advice@addAction' => 'Add new advice',
            'Advice:Admin:Category@addAction' => 'Add new category'
        ),

        'actions' => array(
            'data' => $advices,
            'save' => 'Advice:Admin:Advice@tweakAction',
            'delete' => 'Advice:Admin:Advice@deleteAction'
        )
    )); ?>
</div>

<div class="card">
    <?php $this->loadPartial('items-per-page', array('caption' => 'Advices')); ?>

    <form>
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($advices, array(
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'title'
                    ),

                    array(
                        'column' => 'category',
                        'hidden' => empty($categories)
                    ),

                    array(
                        'column' => 'published',
                        'value' => function($row){
                            return Element::checkbox(sprintf('published[%s]', $row['id']), $row['published']);
                        }
                    )
                ),

                'actions' => array(
                    'edit' => function($row){
                        return Icon::edit(
                            $this->url('Advice:Admin:Advice@editAction', $row['id']),
                            $this->translate('Edit this advice')
                        );
                    },

                    'remove' => function($row){
                        return Icon::remove(
                            $this->url('Advice:Admin:Advice@deleteAction', $row['id']),
                            $this->translate('Remove this advice')
                        );
                    }
                )
            ))); ?>

            <?php if (empty($advices)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No advices'); ?></h2>
            </div>
            <?php endif; ?>

        </div>
    </form>

    <?php $this->loadPartial('paginator'); ?>

</div>

<?php if (!empty($categories)): ?>
<div class="card">
    <h3><?php $this->show('Categories'); ?> <small class="text-muted">(<?= count($categories); ?>)</small></h3>

    <?= $this->widget(new GridViewWidget($categories, array(
        'tableClass' => 'table table-hover table-bordered table-striped',
        'columns' => array(
            array(
                'column' => 'id',
                'label' => '#'
            ),

            array(
                'column' => 'name'
            )
        ),

        'actions' => array(
            'edit' => function($row){
                return Icon::edit(
                    $this->url('Advice:Admin:Category@editAction', $row['id']),
                    $this->translate('Edit this category')
                );
            },

            'remove' => function($row){
                return Icon::remove(
                    $this->url('Advice:Admin:Category@deleteAction', $row['id']),
                    $this->translate('Remove this advice')
                );
            }
        )
    ))); ?>
</div>
<?php endif; ?>
