<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="card">
    <div class="btn-toolbar">
        <div class="dropdown">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            <i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
          </button>

          <div class="dropdown-menu">
             <a class="dropdown-item" href="<?= $this->url('Advice:Admin:Advice@addAction'); ?>"><?php $this->show('Add new advice'); ?></a>
             <a class="dropdown-item" href="<?= $this->url('Advice:Admin:Category@addAction'); ?>"><?php $this->show('Add new category'); ?></a>
             <div class="dropdown-header"><?php $this->show('Actions'); ?></div>
             <?php if (!empty($advices)): ?>
             <a class="dropdown-item" href="#" data-button="save-changes" data-url="<?php echo $this->url('Advice:Admin:Advice@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
             <a class="dropdown-item" href="#" data-button="remove-selected" data-url="<?php echo $this->url('Advice:Admin:Advice@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
             <?php else: ?>
             <a class="dropdown-item disabled"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a>
             <a class="dropdown-item disabled"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>>
             <?php endif; ?>
          </div>
        </div>
    </div>

    <?php $this->loadPartial('items-per-page', array('caption' => 'Advices')); ?>

    <form>
        <div class="table-responsive">
            <?= $this->widget(new GridViewWidget($advices, array(
                'batch' => true,
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'title'
                    ),

                    array(
                        'column' => 'category',
                        'hidden' => empty($categories)
                    ),

                    array(
                        'column' => 'published',
                        'value' => function($row){
                            return Element::checkbox(sprintf('published[%s]', $row['id']), $row['published']);
                        }
                    )
                ),

                'actions' => array(
                    'edit' => function($row){
                        return Icon::edit(
                            $this->url('Advice:Admin:Advice@editAction', $row['id']),
                            $this->translate('Edit this advice')
                        );
                    },

                    'remove' => function($row){
                        return Icon::remove(
                            $this->url('Advice:Admin:Advice@deleteAction', $row['id']),
                            $this->translate('Remove this advice')
                        );
                    }
                )
            ))); ?>

            <?php if (empty($advices)): ?>
            <div class="center-block">
                <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No advices'); ?></h2>
            </div>
            <?php endif; ?>

        </div>
    </form>

    <?php $this->loadPartial('paginator'); ?>

</div>

<?php if (!empty($categories)): ?>
<div class="card">
    <h3><?php $this->show('Categories'); ?> <small class="text-muted">(<?= count($categories); ?>)</small></h3>

    <?= $this->widget(new GridViewWidget($categories, array(
        'tableClass' => 'table table-hover table-bordered table-striped',
        'columns' => array(
            array(
                'column' => 'id',
                'label' => '#'
            ),

            array(
                'column' => 'name'
            )
        ),

        'actions' => array(
            'edit' => function($row){
                return Icon::edit(
                    $this->url('Advice:Admin:Category@editAction', $row['id']),
                    $this->translate('Edit this category')
                );
            },

            'remove' => function($row){
                return Icon::remove(
                    $this->url('Advice:Admin:Category@deleteAction', $row['id']),
                    $this->translate('Remove this advice')
                );
            }
        )
    ))); ?>
</div>
<?php endif; ?>
