<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Advice:Admin:Advice@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new advice'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 
		 <?php if (!empty($advices)): ?>
		 <li><a href="#" data-button="save-changes" data-url="<?php echo $this->url('Advice:Admin:Advice@tweakAction'); ?>"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Advice:Admin:Advice@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save changes'); ?></a></li>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
	  </ul>
	</div>
</div>

<?php $this->loadPartial('items-per-page', array('caption' => 'Advices')); ?>

<form>
    <div class="table-responsive">
        <?= Grid::render($advices, array(
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'title',
                ),

                array(
                    'column' => 'published',
                    'value' => function($row){
                        return Element::checkbox(sprintf('published[%s]', $row['id']), $row['published']);
                    }
                )
            ),

            'actions' => array(
                'edit' => function($row){
                    return Icon::edit(
                        $this->url('Advice:Admin:Advice@editAction', $row['id']),
                        $this->translate('Edit this advice')
                    );
                },

                'remove' => function($row){
                    return Icon::remove(
                        $this->url('Advice:Admin:Advice@deleteAction', $row['id']),
                        $this->translate('Remove this advice')
                    );
                }
            )

        ), $this->translator); ?>

        <?php if (empty($advices)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No advices'); ?></h2>
        </div>
        <?php endif; ?>

    </div>
</form>

<?php $this->loadPartial('paginator'); ?>
